'use client';

// My Files (E8-S3). Lists generated files derived from executions. Until the
// API exposes signed download URLs the Download button is disabled with a
// tooltip; expired files are shown muted. Clean empty-state + table shell.
import { Download, FileText, Inbox } from 'lucide-react';
import { TopBar } from '@/components/shell/TopBar';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useExecutions } from '@/api/hooks';
import { deriveFiles, isExpired } from '@/api/files';
import { fmtBytes, fmtDateTime } from '@/api/format';

export default function FilesPage() {
  const { data, isLoading } = useExecutions();
  const files = deriveFiles(data?.executions ?? []);

  return (
    <>
      <TopBar title="My Files" />
      <main className="flex-1 overflow-auto p-6">
        <p className="mb-4 text-sm text-ink-muted">
          Files generated by your flows. Download links expire after the retention window.
        </p>

        {!isLoading && files.length === 0 ? (
          <Card className="flex flex-col items-center gap-3 p-12 text-center">
            <Inbox className="h-8 w-8 text-ink-subtle" />
            <div>
              <div className="text-sm font-medium text-ink">No files yet</div>
              <p className="mt-1 text-sm text-ink-muted">
                Run a flow that generates a file and it will appear here.
              </p>
            </div>
          </Card>
        ) : (
          <Card className="overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-surface-sunken text-left text-xs uppercase tracking-wide text-ink-subtle">
                  <th className="px-5 py-3 font-medium">File</th>
                  <th className="px-5 py-3 font-medium">Size</th>
                  <th className="px-5 py-3 font-medium">Created</th>
                  <th className="px-5 py-3 font-medium">Expires</th>
                  <th className="px-5 py-3 font-medium sr-only">Download</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {isLoading && (
                  <tr>
                    <td colSpan={5} className="px-5 py-8 text-center text-ink-muted">Loading…</td>
                  </tr>
                )}
                {files.map((f) => {
                  const expired = isExpired(f);
                  return (
                    <tr key={f.id} className="hover:bg-surface-sunken">
                      <td className="px-5 py-3">
                        <div className="flex items-center gap-2.5">
                          <FileText className="h-4 w-4 shrink-0 text-ink-subtle" />
                          <div>
                            <div className="font-medium text-ink">{f.filename}</div>
                            <div className="text-xs text-ink-subtle">
                              {f.flowName} · {f.executionId}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-5 py-3 text-ink-muted tabular-nums">{fmtBytes(f.sizeBytes)}</td>
                      <td className="px-5 py-3 text-ink-muted">{fmtDateTime(f.createdAt)}</td>
                      <td className="px-5 py-3">
                        {expired ? (
                          <Badge className="bg-danger/10 text-danger">Expired</Badge>
                        ) : (
                          <span className="text-ink-muted">{fmtDateTime(f.expiresAt)}</span>
                        )}
                      </td>
                      <td className="px-5 py-3 text-right">
                        <Button
                          size="sm"
                          variant="secondary"
                          disabled={expired}
                          title={expired ? 'Link expired' : `Download ${f.filename}`}
                          aria-label={`Download ${f.filename}`}
                        >
                          <Download className="h-4 w-4" /> Download
                        </Button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </Card>
        )}
      </main>
    </>
  );
}
