'use client';

// Visual query builder (E6-S2). Produces a STRUCTURED spec (queryBuilderSpec) —
// base table, joins, columns, filters — from a connection's schema. No free-form
// SQL: the server compiles + guards the spec (pkg/sqlbuilder). The read-only SQL
// preview is generated by the pure previewSQL() for the analyst's benefit only.
import { Plus, Trash2, Loader2 } from 'lucide-react';
import { cn } from '@/lib/cn';
import { useConnectionSchema } from '@/api/connections';
import {
  JOIN_TYPES,
  FILTER_OPS,
  tablesInPlay,
  previewSQL,
  type QuerySpec,
  type Join,
  type Filter,
  type FilterOp,
  type JoinType,
} from './queryBuilderSpec';

export type QueryBuilderProps = {
  connectionId: string;
  spec: QuerySpec;
  onChange: (spec: QuerySpec) => void;
  maxRows?: number;
};

const inputCls = 'h-8 rounded-md border border-border bg-surface px-2 text-sm outline-none focus:ring-2 focus:ring-brand';

export function QueryBuilder({ connectionId, spec, onChange, maxRows = 1000 }: QueryBuilderProps) {
  const schemaQ = useConnectionSchema(connectionId);
  const tables = schemaQ.data?.tables ?? [];
  const colsOf = (table: string): string[] => tables.find((t) => t.name === table)?.columns.map((c) => c.name) ?? [];

  const patch = (p: Partial<QuerySpec>) => onChange({ ...spec, ...p });

  if (!connectionId) {
    return <p className="text-sm text-ink-muted">Pick a connection first to build a query.</p>;
  }
  if (schemaQ.isLoading) {
    return (
      <p className="flex items-center gap-2 text-sm text-ink-muted">
        <Loader2 className="h-4 w-4 animate-spin" /> Loading schema…
      </p>
    );
  }
  if (schemaQ.isError) {
    return <p className="text-sm text-danger">Could not load the connection schema.</p>;
  }

  const inPlay = tablesInPlay(spec);

  // --- base table ---
  const setTable = (table: string) => patch({ table, columns: [], joins: [], where: [] });

  // --- columns (checkbox per table.column) ---
  const isPicked = (table: string, name: string) => spec.columns.some((c) => c.table === table && c.name === name);
  const toggleColumn = (table: string, name: string) => {
    const picked = isPicked(table, name);
    patch({
      columns: picked
        ? spec.columns.filter((c) => !(c.table === table && c.name === name))
        : [...spec.columns, { table, name }],
    });
  };

  // --- joins ---
  const addJoin = () => patch({ joins: [...(spec.joins ?? []), { type: 'inner', table: '', on: [{ leftTable: spec.table, leftCol: '', rightTable: '', rightCol: '' }] }] });
  const setJoin = (i: number, j: Partial<Join>) => {
    const joins = [...(spec.joins ?? [])];
    joins[i] = { ...joins[i], ...j };
    patch({ joins });
  };
  const setJoinTable = (i: number, table: string) => {
    const joins = [...(spec.joins ?? [])];
    joins[i] = { ...joins[i], table, on: [{ ...joins[i].on[0], rightTable: table }] };
    patch({ joins });
  };
  const setJoinOn = (i: number, o: Partial<Join['on'][number]>) => {
    const joins = [...(spec.joins ?? [])];
    joins[i] = { ...joins[i], on: [{ ...joins[i].on[0], ...o }] };
    patch({ joins });
  };
  const removeJoin = (i: number) => patch({ joins: (spec.joins ?? []).filter((_, k) => k !== i) });

  // --- where ---
  const addFilter = () => patch({ where: [...(spec.where ?? []), { table: spec.table, column: '', op: '=' as FilterOp, value: '' }] });
  const setFilter = (i: number, f: Partial<Filter>) => {
    const where = [...(spec.where ?? [])];
    where[i] = { ...where[i], ...f };
    patch({ where });
  };
  const removeFilter = (i: number) => patch({ where: (spec.where ?? []).filter((_, k) => k !== i) });

  const preview = previewSQL(spec, maxRows);

  return (
    <div className="space-y-4">
      {/* base table */}
      <Section label="From table">
        <select aria-label="Base table" className={cn(inputCls, 'w-full')} value={spec.table} onChange={(e) => setTable(e.target.value)}>
          <option value="">— pick a table —</option>
          {tables.map((t) => (
            <option key={t.name} value={t.name}>{t.name}</option>
          ))}
        </select>
      </Section>

      {spec.table && (
        <>
          {/* joins */}
          <Section
            label="Joins"
            action={
              <button type="button" className="flex items-center gap-1 text-xs text-brand" onClick={addJoin}>
                <Plus className="h-3.5 w-3.5" /> Add join
              </button>
            }
          >
            {(spec.joins ?? []).length === 0 && <p className="text-xs text-ink-subtle">No joins.</p>}
            {(spec.joins ?? []).map((j, i) => (
              <div key={i} className="space-y-2 rounded-md border border-border p-2">
                <div className="flex items-center gap-2">
                  <select aria-label={`Join ${i + 1} type`} className={inputCls} value={j.type} onChange={(e) => setJoin(i, { type: e.target.value as JoinType })}>
                    {JOIN_TYPES.map((jt) => (
                      <option key={jt} value={jt}>{jt}</option>
                    ))}
                  </select>
                  <select aria-label={`Join ${i + 1} table`} className={cn(inputCls, 'flex-1')} value={j.table} onChange={(e) => setJoinTable(i, e.target.value)}>
                    <option value="">— table —</option>
                    {tables.map((t) => (
                      <option key={t.name} value={t.name}>{t.name}</option>
                    ))}
                  </select>
                  <button type="button" aria-label={`Remove join ${i + 1}`} className="text-danger" onClick={() => removeJoin(i)}>
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
                <div className="flex items-center gap-1 text-xs">
                  <span className="text-ink-subtle">ON</span>
                  <select aria-label={`Join ${i + 1} left table`} className={inputCls} value={j.on[0]?.leftTable ?? ''} onChange={(e) => setJoinOn(i, { leftTable: e.target.value })}>
                    <option value="">—</option>
                    {inPlay.map((t) => (
                      <option key={t} value={t}>{t}</option>
                    ))}
                  </select>
                  <select aria-label={`Join ${i + 1} left column`} className={inputCls} value={j.on[0]?.leftCol ?? ''} onChange={(e) => setJoinOn(i, { leftCol: e.target.value })}>
                    <option value="">—</option>
                    {colsOf(j.on[0]?.leftTable ?? '').map((c) => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                  <span>=</span>
                  <select aria-label={`Join ${i + 1} right column`} className={inputCls} value={j.on[0]?.rightCol ?? ''} onChange={(e) => setJoinOn(i, { rightCol: e.target.value })}>
                    <option value="">—</option>
                    {colsOf(j.table).map((c) => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                </div>
              </div>
            ))}
          </Section>

          {/* columns */}
          <Section label="Columns">
            {inPlay.map((t) => (
              <div key={t} className="mb-2">
                <div className="mb-1 text-xs font-medium text-ink-muted">{t}</div>
                <div className="flex flex-wrap gap-1.5">
                  {colsOf(t).map((c) => {
                    const on = isPicked(t, c);
                    return (
                      <label
                        key={c}
                        className={cn('cursor-pointer rounded border px-2 py-0.5 text-xs', on ? 'border-brand bg-brand/10 text-brand-700' : 'border-border text-ink-muted')}
                      >
                        <input type="checkbox" className="sr-only" checked={on} onChange={() => toggleColumn(t, c)} />
                        {c}
                      </label>
                    );
                  })}
                </div>
              </div>
            ))}
          </Section>

          {/* where */}
          <Section
            label="Filters"
            action={
              <button type="button" className="flex items-center gap-1 text-xs text-brand" onClick={addFilter}>
                <Plus className="h-3.5 w-3.5" /> Add filter
              </button>
            }
          >
            {(spec.where ?? []).length > 1 && (
              <div className="mb-2 flex items-center gap-1 text-xs">
                <span className="text-ink-subtle">Match</span>
                <select aria-label="Combinator" className={inputCls} value={spec.combinator ?? 'and'} onChange={(e) => patch({ combinator: e.target.value as 'and' | 'or' })}>
                  <option value="and">ALL (AND)</option>
                  <option value="or">ANY (OR)</option>
                </select>
              </div>
            )}
            {(spec.where ?? []).map((f, i) => (
              <div key={i} className="mb-1.5 flex items-center gap-1">
                <select
                  aria-label={`Filter ${i + 1} column`}
                  className={cn(inputCls, 'flex-1')}
                  value={`${f.table ?? ''}.${f.column}`}
                  onChange={(e) => {
                    const [table, column] = e.target.value.split('.');
                    setFilter(i, { table, column });
                  }}
                >
                  <option value=".">— column —</option>
                  {inPlay.flatMap((t) => colsOf(t).map((c) => (
                    <option key={`${t}.${c}`} value={`${t}.${c}`}>{t}.{c}</option>
                  )))}
                </select>
                <select aria-label={`Filter ${i + 1} operator`} className={inputCls} value={f.op} onChange={(e) => setFilter(i, { op: e.target.value as FilterOp })}>
                  {FILTER_OPS.map((op) => (
                    <option key={op} value={op}>{op}</option>
                  ))}
                </select>
                <input aria-label={`Filter ${i + 1} value`} className={cn(inputCls, 'w-24')} value={f.value} onChange={(e) => setFilter(i, { value: e.target.value })} placeholder="value" />
                <button type="button" aria-label={`Remove filter ${i + 1}`} className="text-danger" onClick={() => removeFilter(i)}>
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            ))}
          </Section>

          {/* limit */}
          <Section label="Row limit">
            <input
              type="number"
              aria-label="Row limit"
              className={cn(inputCls, 'w-28')}
              value={spec.limit ?? ''}
              min={1}
              max={maxRows}
              onChange={(e) => patch({ limit: Number(e.target.value) || undefined })}
            />
            <span className="ml-2 text-xs text-ink-subtle">capped at {maxRows.toLocaleString()} server-side</span>
          </Section>

          {/* preview */}
          <Section label="Generated SQL (read-only)">
            <pre className="overflow-auto rounded-md bg-surface-sunken p-2 text-[11px] leading-relaxed text-ink-muted" data-testid="sql-preview">
              {preview || '—'}
            </pre>
          </Section>
        </>
      )}
    </div>
  );
}

function Section({ label, action, children }: { label: string; action?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <span className="text-sm font-medium text-ink">{label}</span>
        {action}
      </div>
      {children}
    </div>
  );
}
